---
# tasks file for ansible_galaxy_role_ubuntu-locale-japanese

- name: "Set Locale Japanese | Install package"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  apt:
    name: language-pack-ja
    update_cache: yes

# - name: "Set Locale Japanese | Set locale japanese"
#   become: yes
#   ignore_errors: "{{ ansible_check_mode }}"
#   shell:
#     cmd: |
#       echo $LANG | grep "ja_JP.UTF-8" >/dev/null
#       if [ $? -eq 0 ]; then
#         echo "already changed."
#       else
#         update-locale LANG=ja_JP.UTF-8
#       fi

- name: "Set Locale Japanese | Check locale"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  command: cat /etc/default/locale
  register: cat_locale_result

- name: "Set Locale Japanese | Set locale japanese"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  command: update-locale LANG=ja_JP.UTF-8
  when: cat_locale_result.stdout != 'LANG=ja_JP.UTF-8'